SELECT  DISTINCT USER_ID
       , PRODUCT_ID
FROM     (SELECT  USER_ID
                , PRODUCT_ID
                , COUNT(*) OVER(PARTITION BY USER_ID, PRODUCT_ID) CNT
          FROM    ONLINE_SALE) A
WHERE    A.CNT > 1
ORDER BY USER_ID ASC
       , PRODUCT_ID DESC;